name: iOS Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Install CocoaPods dependencies
        run: |
          sudo gem install cocoapods
          pod install
        working-directory: ./psychonautwiki-journal-experiments

      - name: Build the app
        run: xcodebuild -workspace psychonautwiki-journal-experiments.xcworkspace -scheme psychonautwiki-journal-experiments -sdk iphoneos -configuration Release build CODE_SIGNING_ALLOWED=NO

      - name: Run Tests
        run: xcodebuild test -workspace psychonautwiki-journal-experiments.xcworkspace -scheme psychonautwiki-journal-experiments -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
